-- =========================================
-- Usuarios del sistema
-- =========================================
CREATE TABLE USERS (
  USER_ID    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  USERNAME   VARCHAR2(50) NOT NULL UNIQUE,
  EMAIL      VARCHAR2(120) NOT NULL UNIQUE,
  CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- =========================================
-- Credenciales de autenticación
-- method: BASIC | HASH
-- =========================================
CREATE TABLE AUTH_CREDENTIALS (
  CRED_ID     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  USER_ID     NUMBER NOT NULL,
  METHOD      VARCHAR2(20) NOT NULL,  -- BASIC o HASH
  PASSWORD    VARCHAR2(256) NOT NULL, -- texto plano o hash
  CREATED_AT  TIMESTAMP DEFAULT SYSTIMESTAMP,
  CONSTRAINT FK_AUTH_USER FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

-- =========================================
-- Login con Google
-- =========================================
CREATE TABLE OAUTH_ACCOUNT (
  OAUTH_ID          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  USER_ID           NUMBER NOT NULL,
  PROVIDER_USER_ID  VARCHAR2(128) NOT NULL, -- sub de Google
  EMAIL             VARCHAR2(120) NOT NULL,
  CREATED_AT        TIMESTAMP DEFAULT SYSTIMESTAMP,
  CONSTRAINT FK_OAUTH_USER FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

-- =========================================
-- Auditoría de inicios de sesión
-- =========================================
CREATE TABLE LOGIN_AUDIT (
  LOGIN_ID   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  USER_ID    NUMBER,                -- puede ser NULL si fallo sin usuario válido
  METHOD     VARCHAR2(20) NOT NULL, -- BASIC | HASH | GOOGLE
  SUCCESS    NUMBER(1) NOT NULL,    -- 1=ok, 0=fallo
  CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
  CONSTRAINT FK_AUDIT_USER FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

-- =========================================
-- Inventario de vehículos
-- =========================================
CREATE TABLE VEHICLES (
  VEHICLE_ID  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  BRAND       VARCHAR2(50) NOT NULL,
  MODEL       VARCHAR2(80) NOT NULL,
  YEAR_MADE   NUMBER(4)    NOT NULL,
  PRICE       NUMBER(12,2) NOT NULL,
  STATUS      VARCHAR2(20) DEFAULT 'DISPONIBLE', -- DISPONIBLE | VENDIDO | MANTENIMIENTO
  MILEAGE_KM  NUMBER(10),
  COLOR       VARCHAR2(40),
  CREATED_AT  TIMESTAMP DEFAULT SYSTIMESTAMP
);
